### ISSUE TITLE
Optimizations for larger number of files in a dataset (weird stuff happens with many files)

### ISSUE THREAD

**Issue by sfisher** [datadryad/dryad-product-roadmap#2947]
These problems are more apparent on my local machine because of network latency to the database at AWS, but I believe they exist in all environments to some degree or other.

1.  Going to the review page with a large number of files uploaded to S3 (not at URLs) takes a long time to load since part of the review is checking that the indicated files are really stored on S3 before continuing.
2. Hitting the submit button pauses for a very long time, in a similar way.
3. The operations involving a submission seem to be very inefficient with lots and lots of instances of resources and curation activities loading repeatedly like lines below.  I assume this is because of some badly designed callbacks somewhere in the chain of files/resources/curation_activities.  Like it seems to reload these records many hundreds of times if there are hundreds of files.

```
StashEngine::Resource Load (86.1ms)  SELECT `stash_engine_resources`.* FROM `stash_engine_resources` WHERE `stash_engine_resources`.`id` = 4211 LIMIT 1
  ↳ app/models/stash_engine/data_file.rb:153:in `s3_staged_presigned_url'
  StashEngine::CurationActivity Load (89.3ms)  SELECT `stash_engine_curation_activities`.* FROM `stash_engine_curation_activities` WHERE `stash_engine_curation_activities`.`resource_id` = 4211 ORDER BY `stash_engine_curation_activities`.`id` ASC
  ↳ app/models/stash_engine/data_file.rb:153:in `s3_staged_presigned_url'
  StashEngine::Resource Load (81.0ms)  SELECT `stash_engine_resources`.* FROM `stash_engine_resources` WHERE `stash_engine_resources`.`id` = 4211 LIMIT 1
  ↳ app/models/stash_engine/data_file.rb:153:in `s3_staged_presigned_url'
  StashEngine::CurationActivity Load (169.6ms)  SELECT `stash_engine_curation_activities`.* FROM `stash_engine_curation_activities` WHERE `stash_engine_curation_activities`.`resource_id` = 4211 ORDER BY `stash_engine_curation_activities`.`id` ASC
  ↳ app/models/stash_engine/data_file.rb:153:in `s3_staged_presigned_url'
  StashEngine::Resource Load (58.6ms)  SELECT `stash_engine_resources`.* FROM `stash_engine_resources` WHERE `stash_engine_resources`.`id` = 4211 LIMIT 1
  ↳ app/models/stash_engine/data_file.rb:153:in `s3_staged_presigned_url'
  StashEngine::CurationActivity Load (86.3ms)  SELECT `stash_engine_curation_activities`.* FROM `stash_engine_curation_activities` WHERE `stash_engine_curation_activities`.`resource_id` = 4211 ORDER BY `stash_engine_curation_activities`.`id` ASC
  ↳ app/models/stash_engine/data_file.rb:153:in `s3_staged_presigned_url'
  StashEngine::Resource Load (74.7ms)  SELECT `stash_engine_resources`.* FROM `stash_engine_resources` WHERE `stash_engine_resources`.`id` = 4211 LIMIT 1
  ↳ app/models/stash_engine/data_file.rb:153:in `s3_staged_presigned_url'
  StashEngine::CurationActivity Load (68.5ms)  SELECT `stash_engine_curation_activities`.* FROM `stash_engine_curation_activities` WHERE `stash_engine_curation_activities`.`resource_id` = 4211 ORDER BY `stash_engine_curation_activities`.`id` ASC
  ↳ app/models/stash_engine/data_file.rb:153:in `s3_staged_presigned_url'
  StashEngine::Resource Load (93.5ms)  SELECT `stash_engine_resources`.* FROM `stash_engine_resources` WHERE `stash_engine_resources`.`id` = 4211 LIMIT 1
  ↳ app/models/stash_engine/data_file.rb:153:in `s3_staged_presigned_url'
  StashEngine::CurationActivity Load (82.0ms)  SELECT `stash_engine_curation_activities`.* FROM `stash_engine_curation_activities` WHERE `stash_engine_curation_activities`.`resource_id` = 4211 ORDER BY `stash_engine_curation_activities`.`id` ASC
```

I think callbacks on ActiveRecord models can be something of an anti-pattern if there is some more predictable way to do things or if one callback makes others happen in an unpredictable way.  They have their uses, but this case seems to be a good example of why they're a PITA.

IDK if I agree with everything he writes, but 
https://medium.com/planet-arkency/the-biggest-rails-code-smell-you-should-avoid-to-keep-your-app-healthy-a61fd75ab2d3

**Comment by alinvetian** [comment]
The problem with this page is the S3 check for dataset files
https://github.com/datadryad/dryad-app/blob/fca29f2c728fcf8176bf132ca98e635022d44340/app/models/stash_datacite/resource/dataset_validations.rb#L234

We need to decide how to improve this in the new submission system.

**Comment by ahamelers** [comment]
In the new system there are no checks to s3 currently. One will need to be added.

I think the best thing to do would be to combine with #1802 and check for URLs on the upload page.
